### ISSUE TITLE
Clair can't parse the overloading for the operator ()

### ISSUE THREAD

**Issue by ruichen-ing** [usethesource/clair#56]
I use clair-0.8.3-RC2 to generate a M3 model for a source file and get the following error:
```
|lib://clair/src/lang/cpp/M3.rsc%7C(9636,225,<176,0>,<177,188>): Java("RuntimeException","unexpected null argument in resolveITypedef)
        at lang.cpp.internal.TypeResolver.lambda$resolveITypedef$6(|unknown:///TypeResolver.java|(0,0,<710,0>,<710,0>))
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(|unknown:///Spliterators.java|(0,0,<948,0>,<948,0>))
        at java.util.stream.ReferencePipeline$Head.forEach(|unknown:///ReferencePipeline.java|(0,0,<658,0>,<658,0>))
        at lang.cpp.internal.TypeResolver.resolveITypedef(|unknown:///TypeResolver.java|(0,0,<698,0>,<698,0>))
        at lang.cpp.internal.TypeResolver.resolveType(|unknown:///TypeResolver.java|(0,0,<297,0>,<297,0>))
        at lang.cpp.internal.TypeResolver.resolveIFunctionType(|unknown:///TypeResolver.java|(0,0,<631,0>,<631,0>))
        at lang.cpp.internal.TypeResolver.resolveType(|unknown:///TypeResolver.java|(0,0,<279,0>,<279,0>))
        at lang.cpp.internal.TypeResolver.resolveICPPASTDeclarator(|unknown:///TypeResolver.java|(0,0,<158,0>,<158,0>))
        ...
```
The source code leading to the error is the `operator()` in the following snippet:
```
template <typename... ArgRefs>
internal::call_result_t<Callable, ArgRefs...> operator()(
    ArgRefs&&... args) const {
  return std::move(*callable_)(std::forward<ArgRefs>(args)...);
}
```
It seems Clair can't match this overloading pattern and regards it as a function with null argument.

**Comment by ruichen-ing** [comment]
After setting the stack trace:
```
rascal>:set errors true
```
I get the following information:
```
rascal>createM3FromCppFile(source, stdLib=STD_LIB+getFirstFrom(sourceToStdlibRel[source]), includeDirs=getFirstFrom(sourceToIncRel[source]))
)
Include sscfts1/windowseventloop.h for C:\driveD\dev\y\root\PosGen\sscf\vxw\include\sscfts1.h not found
java.lang.RuntimeException: unexpected null argument in resolveITypedef @ |file:///C:/driveD/dev/y/root/Externals/Philips.3rdParty.GoogleTest/lib/v142_x86_md/include/gmock/gmock-actions.h|(21591,10)
        at lang.cpp.internal.TypeResolver.lambda$resolveITypedef$6(TypeResolver.java:710)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at lang.cpp.internal.TypeResolver.resolveITypedef(TypeResolver.java:698)
        at lang.cpp.internal.TypeResolver.resolveType(TypeResolver.java:297)
        at lang.cpp.internal.TypeResolver.resolveIFunctionType(TypeResolver.java:631)
        at lang.cpp.internal.TypeResolver.resolveType(TypeResolver.java:279)
        at lang.cpp.internal.TypeResolver.resolveICPPASTDeclarator(TypeResolver.java:158)
        at lang.cpp.internal.TypeResolver.resolveType(TypeResolver.java:147)
        at lang.cpp.internal.Parser.visit(Parser.java:1149)
        at lang.cpp.internal.Parser.visit(Parser.java:882)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTFunctionDefinition.accept(CPPASTFunctionDefinition.java:191)
        at lang.cpp.internal.Parser.visit(Parser.java:1024)
        at lang.cpp.internal.Parser.visit(Parser.java:909)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTTemplateDeclaration.accept(CPPASTTemplateDeclaration.java:115)
        at lang.cpp.internal.Parser.lambda$visit$35(Parser.java:1818)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at lang.cpp.internal.Parser.visit(Parser.java:1817)
        at lang.cpp.internal.Parser.visit(Parser.java:1756)
        at lang.cpp.internal.Parser.visit(Parser.java:1733)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTCompositeTypeSpecifier.accept(CPPASTCompositeTypeSpecifier.java:174)
        at lang.cpp.internal.Parser.visit(Parser.java:1200)
        at lang.cpp.internal.Parser.visit(Parser.java:885)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTSimpleDeclaration.accept(CPPASTSimpleDeclaration.java:100)
        at lang.cpp.internal.Parser.visit(Parser.java:1024)
        at lang.cpp.internal.Parser.visit(Parser.java:909)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTTemplateDeclaration.accept(CPPASTTemplateDeclaration.java:115)
        at lang.cpp.internal.Parser.lambda$visit$35(Parser.java:1818)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at lang.cpp.internal.Parser.visit(Parser.java:1817)
        at lang.cpp.internal.Parser.visit(Parser.java:1756)
        at lang.cpp.internal.Parser.visit(Parser.java:1733)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTCompositeTypeSpecifier.accept(CPPASTCompositeTypeSpecifier.java:174)
        at lang.cpp.internal.Parser.visit(Parser.java:1200)
        at lang.cpp.internal.Parser.visit(Parser.java:885)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTSimpleDeclaration.accept(CPPASTSimpleDeclaration.java:100)
        at lang.cpp.internal.Parser.visit(Parser.java:1024)
        at lang.cpp.internal.Parser.visit(Parser.java:909)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTTemplateDeclaration.accept(CPPASTTemplateDeclaration.java:115)
        at lang.cpp.internal.Parser.lambda$visit$48(Parser.java:3790)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at lang.cpp.internal.Parser.visit(Parser.java:3789)
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTNamespaceDefinition.accept(CPPASTNamespaceDefinition.java:123)
        at lang.cpp.internal.Parser.visit(Parser.java:759)
        at org.eclipse.cdt.internal.core.dom.parser.ASTTranslationUnit.accept(ASTTranslationUnit.java:278)
        at lang.cpp.internal.Parser.convertCdtToRascal(Parser.java:556)
        at lang.cpp.internal.Parser.parseCppToM3AndAst(Parser.java:427)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.rascalmpl.interpreter.result.JavaMethod.invoke(JavaMethod.java:241)
        at org.rascalmpl.interpreter.result.JavaMethod.call(JavaMethod.java:163)
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:540)
        at org.rascalmpl.semantics.dynamic.Declarator$Default.interpret(Declarator.java:52)
        at org.rascalmpl.semantics.dynamic.LocalVariableDeclaration$Default.interpret(LocalVariableDeclaration.java:36)
        at org.rascalmpl.semantics.dynamic.Statement$VariableDeclaration.interpret(Statement.java:1003)
        at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:385)
        at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:326)
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:540)
        at org.rascalmpl.semantics.dynamic.Command$Expression.interpret(Command.java:61)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:1094)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:955)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:908)
        at org.rascalmpl.repl.RascalInterpreterREPL.evalStatement(RascalInterpreterREPL.java:132)
        at org.rascalmpl.repl.BaseRascalREPL.handleInput(BaseRascalREPL.java:106)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1.handleInput(LSPTerminalREPL.java:191)
        at org.rascalmpl.repl.BaseREPL.handleInput(BaseREPL.java:180)
        at org.rascalmpl.repl.BaseREPL.run(BaseREPL.java:347)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL.main(LSPTerminalREPL.java:269)
|lib://clair/src/lang/cpp/M3.rsc|(9454,225,<173,0>,<174,188>): Java("RuntimeException","unexpected null argument in resolveITypedef @ |file:///C:/driveD/dev/y/root/Externals/Philips.3rdParty.GoogleTest/lib/v142_x86_md/include/gmock/gmock-actions.h|(21591,10)")
        at lang.cpp.internal.TypeResolver.lambda$resolveITypedef$6(|unknown:///TypeResolver.java|(0,0,<710,0>,<710,0>))
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(|unknown:///Spliterators.java|(0,0,<948,0>,<948,0>))
        at java.util.stream.ReferencePipeline$Head.forEach(|unknown:///ReferencePipeline.java|(0,0,<658,0>,<658,0>))
        at lang.cpp.internal.TypeResolver.resolveITypedef(|unknown:///TypeResolver.java|(0,0,<698,0>,<698,0>))
        at lang.cpp.internal.TypeResolver.resolveType(|unknown:///TypeResolver.java|(0,0,<297,0>,<297,0>))
        at lang.cpp.internal.TypeResolver.resolveIFunctionType(|unknown:///TypeResolver.java|(0,0,<631,0>,<631,0>))
        at lang.cpp.internal.TypeResolver.resolveType(|unknown:///TypeResolver.java|(0,0,<279,0>,<279,0>))
        at lang.cpp.internal.TypeResolver.resolveICPPASTDeclarator(|unknown:///TypeResolver.java|(0,0,<158,0>,<158,0>))
        at lang.cpp.internal.TypeResolver.resolveType(|unknown:///TypeResolver.java|(0,0,<147,0>,<147,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1149,0>,<1149,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<882,0>,<882,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTFunctionDefinition.accept(|unknown:///CPPASTFunctionDefinition.java|(0,0,<191,0>,<191,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1024,0>,<1024,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<909,0>,<909,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTTemplateDeclaration.accept(|unknown:///CPPASTTemplateDeclaration.java|(0,0,<115,0>,<115,0>))
        at lang.cpp.internal.Parser.lambda$visit$35(|unknown:///Parser.java|(0,0,<1818,0>,<1818,0>))
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(|unknown:///Spliterators.java|(0,0,<948,0>,<948,0>))
        at java.util.stream.ReferencePipeline$Head.forEach(|unknown:///ReferencePipeline.java|(0,0,<658,0>,<658,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1817,0>,<1817,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1756,0>,<1756,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1733,0>,<1733,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTCompositeTypeSpecifier.accept(|unknown:///CPPASTCompositeTypeSpecifier.java|(0,0,<174,0>,<174,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1200,0>,<1200,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<885,0>,<885,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTSimpleDeclaration.accept(|unknown:///CPPASTSimpleDeclaration.java|(0,0,<100,0>,<100,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1024,0>,<1024,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<909,0>,<909,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTTemplateDeclaration.accept(|unknown:///CPPASTTemplateDeclaration.java|(0,0,<115,0>,<115,0>))
        at lang.cpp.internal.Parser.lambda$visit$35(|unknown:///Parser.java|(0,0,<1818,0>,<1818,0>))
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(|unknown:///Spliterators.java|(0,0,<948,0>,<948,0>))
        at java.util.stream.ReferencePipeline$Head.forEach(|unknown:///ReferencePipeline.java|(0,0,<658,0>,<658,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1817,0>,<1817,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1756,0>,<1756,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1733,0>,<1733,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTCompositeTypeSpecifier.accept(|unknown:///CPPASTCompositeTypeSpecifier.java|(0,0,<174,0>,<174,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1200,0>,<1200,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<885,0>,<885,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTSimpleDeclaration.accept(|unknown:///CPPASTSimpleDeclaration.java|(0,0,<100,0>,<100,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<1024,0>,<1024,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<909,0>,<909,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTTemplateDeclaration.accept(|unknown:///CPPASTTemplateDeclaration.java|(0,0,<115,0>,<115,0>))
        at lang.cpp.internal.Parser.lambda$visit$48(|unknown:///Parser.java|(0,0,<3790,0>,<3790,0>))
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(|unknown:///Spliterators.java|(0,0,<948,0>,<948,0>))
        at java.util.stream.ReferencePipeline$Head.forEach(|unknown:///ReferencePipeline.java|(0,0,<658,0>,<658,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<3789,0>,<3789,0>))
        at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTNamespaceDefinition.accept(|unknown:///CPPASTNamespaceDefinition.java|(0,0,<123,0>,<123,0>))
        at lang.cpp.internal.Parser.visit(|unknown:///Parser.java|(0,0,<759,0>,<759,0>))
        at org.eclipse.cdt.internal.core.dom.parser.ASTTranslationUnit.accept(|unknown:///ASTTranslationUnit.java|(0,0,<278,0>,<278,0>))
        at lang.cpp.internal.Parser.convertCdtToRascal(|unknown:///Parser.java|(0,0,<556,0>,<556,0>))
        at lang.cpp.internal.Parser.parseCppToM3AndAst(|unknown:///Parser.java|(0,0,<427,0>,<427,0>))
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(|unknown:///NativeMethodAccessorImpl.java|(0,0,<0,0>,<0,0>))
        at parseCppToM3AndAst(|lib://clair/src/lang/cpp/M3.rsc|(8526,13,<159,157>,<159,170>))
        at $shell$(|prompt:///|(12,4,<1,12>,<1,16>)WARNING: ResourcesPlugin was null, can't get workspace; not overriding include files
ok
```

**Comment by jurgenvinju** [comment]
* By overloading the `()` operator you effectively create a method that can take an arbitrary amount of arguments. This is what the code is supposed to do.

**Comment by jurgenvinju** [comment]
ChatGPT explains:

> This C++ template defines an operator() function that takes a variable number of arguments (ArgRefs&&... args). It is a  member function of a class or a struct, where Callable is the type of the callable object stored in the callable_ member variable.

> The return type of the operator() function is determined by internal::call_result_t<Callable, ArgRefs...>. call_result_t is a helper template that deduces the return type of a function call with the given arguments. It is typically used to deduce the return type of a callable object.

> Inside the function body, the operator() function invokes the callable object callable_ by forwarding the provided arguments (std::forward<ArgRefs>(args)...). The std::move function is used to cast callable_ to an rvalue reference before invoking it. This is done to enable potential move semantics in the invocation.

> In summary, this template allows you to invoke a callable object stored in the callable_ member variable of a class or struct. The return type of the invocation is determined by call_result_t, which deduces it based on the callable object's return type and the provided arguments.
